BigBang/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls', namespace='polls', app_name='polls')),
    url(r'^summarizer/', include('summarizer.urls', namespace='summarizer', app_name='summarizer')),
]

polls/urls.py
from django.conf.urls import url
from polls import views
from django.contrib.auth.decorators import login_required

app_name = 'polls'

urlpatterns = [
	url(r'^$', login_required(views.IndexView.as_view()), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^election/result/$', views.ElectionResultsView.as_view(), name='election_result'),
	url(r'^login/$', views.show_login, name='login'),
	url(r'^login/attempt/$', views.attempt_login, name='attempt_login'),
	url(r'^logout/$', views.do_logout, name='logout'),
	url(r'^vote/$', views.vote_, name='vote_'),
]

summarizer/urls.py
from django.conf.urls import url
from summarizer import views

urlpatterns = [
 url(r'^$', views.index, name='index'),
 url(r'^summarize/', views.summarize, name='summarize'),
]

blog2social/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	"""docstring for Question"""
	question_text = models.CharField(max_length = 250)
	pub_date = models.DateTimeField('Date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
	"""docstring for Choice"""
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default = 0)

	def __str__(self):
		return self.choice_text



		
		

summarizer/models.py
from django.db import models

# Create your models here.

blog2social/views.py
from django.shortcuts import render

# Create your views here.

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from polls.models import Question, Choice
from django.db.models import F
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout

# Create your views here.

class IndexView(generic.ListView):
	"""Docstring for IndexView"""
	template_name = "polls/index.html"
	context_object_name = "latest_questions"

	def get_queryset(self):
		"""Return the last five polls"""
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
			

class DetailView(generic.DetailView):
	"""docstring for DetailView"""
	model = Question
	template_name = "polls/detail.html"
	
class ResultsView(generic.DetailView):
	"""docstring for ResultsView"""
	model = Question
	template_name = "polls/results.html"
		
class ElectionResultsView(generic.ListView):
	"""docstring for ElectionResultView"""
	context_object_name = "questions"
	template_name = "polls/election_result.html"
	
	def get_queryset(self):
		return Question.objects.all().order_by('id')

def show_login(request):
	template = loader.get_template('polls/login.html')
	return HttpResponse(template.render({}, request))

def vote_(request):
	return HttpResponse(request.POST)
	pass

def vote(request, question_id):
	question = Question.objects.get(pk = question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		template = loader.get_template('polls/detail.html')
		return HttpResponse(template.render({'question': question}, request))
	else:
		selected_choice.votes = F('votes') + 1  # avoids race condition
		selected_choice.save()
		logout(request)
		return HttpResponseRedirect(reverse('polls:index'))

def attempt_login(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(request, username=username, password=password)
	if user is not None:
		login(request, user)
		return HttpResponseRedirect(reverse('polls:index'))
	else:
		return HttpResponseRedirect(reverse('polls:login'))

def do_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('polls:login'))

summarizer/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import get_template

import Algorithmia

# Create your views here.

def index(request):
	template = get_template('summarizer/index.html')
	return HttpResponse(template.render({}, request))

def summarize(request):
	_input = request.POST['text_input']
	client = Algorithmia.client('simpjKSYTfqHFpp/lOw4ViLFeTo1')
	algorithm = client.algo('nlp/Summarizer/0.1.6')
	response = algorithm.pipe(_input)
	return HttpResponse(response.result)

polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Poll Results | {{ question.question_text }}</title>
	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
	<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
</head>
<body>
	<nav class="pink darken-4" role="navigation">
		<div class="nav-wrapper container">
			<a href="{% url 'polls:index' %}" title="Home" class="brand-logo">NASS Poll</a>
			<ul class="right hide-on-med-and-down">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<ul class="side-nav" id="nav-mobile">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<a href="#" data-activates="nav-mobile" class="button-collapse"><i class="fa fa-globle"></i></a>
		</div>
	</nav>
	<!-- End nav -->
	<div class="container">
		<div class="row">
			<div class="col l12 s12">
				<h3 class="center orange-text">Question - {{ question.question_text }}</h3>
				<div class="divider"></div>
				<form action="{% url 'polls:vote' question.id %}" method="POST" accept-charset="utf-8">
					{% csrf_token %}
					{% for choice in question.choice_set.all %}
						<p class="">
							<input required type="radio" name="choice" value="{{ choice.id }}" id="choice{{ forloop.counter }}">
							<label for="choice{{ forloop.counter }}" class="red-text darken-2">{{ choice.choice_text }}</label>
						</p>
					{% endfor %}
					<button type="submit" class="btn btn-large green darken-4">Vote Now!</button>
				</form>
			</div>
		</div>
	</div>
	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
</body>
</html>

polls/templates/polls/election_result.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>All Election Result</title>
	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" />
	<link rel="stylesheet" href="{% static 'css/font-awesome-4.7.0/css/font-awesome.min.css' %}" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
	<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
</head>
<body>
	<nav class="pink darken-4" role="navigation">
		<div class="nav-wrapper container">
			<a href="#!" title="Home" class="brand-logo">NASS Poll</a>
			<ul class="right hide-on-med-and-down">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<ul class="side-nav" id="nav-mobile">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<a href="#" data-activates="nav-mobile" class="button-collapse"><i class="fa fa-globe"></i></a>
		</div>
	</nav>
	</div>
	<div class="container">
		<div class="row">
			<div class="col l12">
				{% if questions %}
					{% for question in questions %}
						<div class="card-panel teal">
							<h5>{{ question.question_text }}</h5>
							<div class="divider"></div>
							<div class="collection">
								{% for choice in question.choice_set.all %}
									<p class="collection-item">{{ choice.choice_text }} <span class="new badge">{{ choice.votes }} votes</span></p>
								{% endfor %}
							</div>
							<a href="{% url 'polls:results' question.id %}" title="More detail" class="btn black" target="__blank">Detail</a>
						</div>
					{% endfor %}
				{% else %}
					<h2 class="center text-darken-4 red">No Election Results!</h2>
				{% endif %}
			</div>
		</div>
	</div>
	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
</body>
</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Home | Polls</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/materialize.min.css' %}" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
	<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
</head>
<body>
	<!-- Navigation -->
	<nav class="pink darken-4" role="navigation">
		<div class="nav-wrapper container pin-top">
			<a href="{% url 'polls:index' %}" title="Home" class="brand-logo">NASS Poll</a>
			<ul class="right hide-on-med-and-down">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<ul class="side-nav" id="nav-mobile">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">Menu</i></a>
		</div>
	</nav>
	<!-- End nav -->
	<!-- Top section -->
	<div class="section no-pad-bot" id="index-banner">
	    <div class="container">
	      	<br><br>
	      	<h3 class="header center orange-text">NASS ELECTION 2018</h3>
	      	<div class="row center">
	        	<h5 class="header col s12 light">NASS polling application was built on top Python Django Framework</h5>
	      </div>
	      <div class="row center">
	      	<a href="#" id="download-button" class="btn-large waves-effect waves-light orange">How it Works</a>
	      </div>
	      <br><br>
	    </div>
	</div>
	<!-- End top section -->
	<div class="container">
		<div class="row">
			<div class="col l12">
				<h3 class="center orange-text">POLLS AVAILABLE</h3><hr>
				{% if latest_questions %}
					<ul>
						{% for question in latest_questions %}
							<li><h5>{{ question.question_text }}</h5><a href="{% url 'polls:detail' question.id %}" class="btn btn-small orange darken-4 waves-effect" name="button{{ question.id }}">Vote Now!</a></li>
						{% endfor %}
					</ul>
				{% else %}
					<h3 class="center orange-text text-darken-4">No polls available.</h3>
				{% endif %}
			</div>
		</div>
	</div>

	<!-- footer  -->
	<footer class="page-footer teal darken-4">
	    <div class="container">
	      	<div class="row">
	        <div class="col l6 s12">
	          	<h5 class="white-text">About BigBang</h5>
	          	<p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>
	        </div>
	        <div class="col l3 s12">
	          	<h5 class="white-text">Join The Team</h5><div class="divider"></div>
	          	<ul>
		            <li><a class="white-text" href="#!">IRC Channel</a></li>
		            <li><a class="white-text" href="#!">Slack Bot</a></li>
		            <li><a class="white-text" target="__blank" href="mailto:akeem@thenass.org.ng">Email Us</a></li>
		            <li><a class="white-text" href="#!">Air Break</a></li>
	          	</ul>
	        </div>
	        <div class="col l3 s12">
	      	    <h5 class="white-text">Connect With Us</h5><div class="divider"></div>
	        	<ul>
		            <li><a class="white-text" href="#!">Facebook</a></li>
		            <li><a class="white-text" href="#!">Instagram</a></li>
		            <li><a class="white-text" href="#!">Twitter</a></li>
		            <li><a class="white-text" href="#!">LinkedIn</a></li>
	          	</ul>
	        </div>
	      </div>
	    </div>
	    <div class="footer-copyright">
	      	<div class="container">
	      		Built By <a class="orange-text text-lighten-3" target="__blank" href="https://dev-haykay.github.io">Y.A.P__</a>
	      		<span class="right">All Rights Reserved. BigBang &copy; 2017. <strong>RC 121618</strong></span>
	      	</div>
	    </div>
 	</footer>
 	<!-- footer ends -->


	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
</body>
</html>

polls/templates/polls/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Home | Login</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/materialize.min.css' %}" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
	<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
</head>
<body>
	<!-- Navigation -->
	<nav class="pink darken-4" role="navigation">
		<div class="nav-wrapper container pin-top">
			<a href="{% url 'polls:index' %}" title="Home" class="brand-logo">NASS Poll</a>
			<ul class="right hide-on-med-and-down">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<ul class="side-nav" id="nav-mobile">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">Menu</i></a>
		</div>
	</nav>
	<!-- End nav -->
	<div class="container">
		<div class="row">
			<div class="col l12">
				<h3 class="center black-text">LOGIN HERE TO VOTE</h3>
				<div class="divider"></div><br><br><br>
				<form action="{% url 'polls:attempt_login' %}" method="POST" accept-charset="utf-8" class="col s12">
					{% csrf_token %}
					<div class="row">
						<div class="input-field col s6">
							<input type="text" name="username" value="" placeholder="Username" required class="validate">
							<label for="username">USERNAME</label>
						</div>
						<div class="input-field col s6">
							<input type="password" name="password" value="" placeholder="Password" required class="validate">
							<label for="password">PASSWORD</label>
						</div>
					</div>
					<BUTTON type="submit" class="btn btn-large">Login</BUTTON>
				</form>
			</div>
		</div>
	</div>

	<!-- footer  -->
	<footer class="page-footer teal darken-4">
	    <div class="container">
	      	<div class="row">
	        <div class="col l6 s12">
	          	<h5 class="white-text">About BigBang</h5>
	          	<p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>
	        </div>
	        <div class="col l3 s12">
	          	<h5 class="white-text">Join The Team</h5><div class="divider"></div>
	          	<ul>
		            <li><a class="white-text" href="#!">IRC Channel</a></li>
		            <li><a class="white-text" href="#!">Slack Bot</a></li>
		            <li><a class="white-text" target="__blank" href="mailto:akeem@thenass.org.ng">Email Us</a></li>
		            <li><a class="white-text" href="#!">Air Break</a></li>
	          	</ul>
	        </div>
	        <div class="col l3 s12">
	      	    <h5 class="white-text">Connect With Us</h5><div class="divider"></div>
	        	<ul>
		            <li><a class="white-text" href="#!">Facebook</a></li>
		            <li><a class="white-text" href="#!">Instagram</a></li>
		            <li><a class="white-text" href="#!">Twitter</a></li>
		            <li><a class="white-text" href="#!">LinkedIn</a></li>
	          	</ul>
	        </div>
	      </div>
	    </div>
	    <div class="footer-copyright">
	      	<div class="container">
	      		Built By <a class="orange-text text-lighten-3" target="__blank" href="https://dev-haykay.github.io">Y.A.P__</a>
	      		<span class="right">All Rights Reserved. BigBang &copy; 2017. <strong>RC 121618</strong></span>
	      	</div>
	    </div>
 	</footer>
 	<!-- footer ends -->


	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
</body>
</html>

polls/templates/polls/results.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Poll Results | {{ question.question_text }}</title>
	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
	<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
</head>
<body>
	<nav class="pink darken-4" role="navigation">
		<div class="nav-wrapper container">
			<a href="{% url 'polls:election_result' %}" title="Home" class="brand-logo">NASS Poll</a>
			<ul class="right hide-on-med-and-down">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<ul class="side-nav" id="nav-mobile">
				<li><a href="#" title="">Polls</a></li>
				<li><a href="#" title="">How it Works</a></li>
				<li><a href="#" title="">Register</a></li>
				<li><a href="#" title="">About</a></li>
			</ul>
			<a href="#" data-activates="nav-mobile" class="button-collapse"><i class="fa fa-globle"></i></a>
		</div>
	</nav>

	<!-- End nav -->

	<div class="container">
		<div class="row">
			<div class="col l12 s12"><br>
				<h4 class="center orange-text text-darken-4">Results For - <a href="#!" title="">{{ question.question_text }}</a></h4><div class="divider"></div>
				{% for choice in question.choice_set.all %}
					<h6 style="font-size: 17px;">{{ forloop.counter }}. {{ choice.choice_text }} - {{ choice.votes }} votes
					</h6>
					<div class="progress red darken-2" style="width: {{ choice.votes }}%; height: 30px;" title="{{ choice.choice_text }} - {{ choice.votes }} votes"></div><div class="divider"></div>
				{% endfor %}
			</div>
			<div class="col l12 s12">
				<div id="chart" style="height: 500px; width: 100%">
					<!-- For Visualization -->
				</div>
			</div>
		</div>
	</div>
	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
	<script src="{% static 'js/canvas.min.js' %}"></script>
	<script>
		var dpoints = [];
		{% for choice in question.choice_set.all %}
			dpoints.push({
				y: {{ choice.votes }},
				label: "{{ choice.choice_text }}"
			});
		{% endfor %}
		window.onload = function (args) {
			/* body... */
			var chart = new CanvasJS.Chart("chart", {
				animationEnabled: true,
				title: {
					text: "",
					horizontalAlign: "left"
				},
				data: [{
					type: "doughnut",
					startAngle: 60,
					indexLabelFontSize: 17,
					indexLabel: "{label} - #percent%",
					toolTipContent: "<b>{label}:</b> {y} (#percent%)",
					dataPoints: dpoints
				}]
			});
			chart.render();
		}
	</script>
</body>
</html>

summarizer/templates/summarizer/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Home | Summarizer</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<style>
		body {
			padding: 2em;
			font-weight: 300;
			font-family: 'Lato', 'Helvetica', sans-serif;
			line-height: 1.7;
		}
	</style>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-7 col-md-offset-3">
				<h2 style="text-align: center;">Welcome to Summarizer App</h2><br><br><hr style="background-color: #DA5D31;">
				<form action="/summarizer/summarize/" method="POST" accept-charset="utf-8">
					{% csrf_token %}
					<div class="form-group">
						<label for="text_input"><h4>Enter some text here!</h4></label>
						<textarea name="text_input" class="form-control" required rows="12"></textarea>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-lg btn-block">Summarize Now</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</body>
</html>